import { test, expect, type Locator } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { TEMPLATES, LANGS } from './helpers/routes';
import { AXE_TAGS, structuralScan, contrastScan } from './helpers/axe';
import { forceTheme } from './helpers/theme';
import { routeAvatar, GROUNDED_EN } from './helpers/avatar-sse';

/**
 * Task 29 — accessibility pass (axe + explicit landmark/focus checks). Built from
 * an EMPIRICAL pre-scan of the live build (Decisions B/F), not the plan's
 * hypothesis. Two `toEqual([])` axe gates, each with a recorded contingency:
 *
 *  - STRUCTURAL matrix (every WCAG 2 A/AA rule except color-contrast): the site is
 *    clean EXCEPT one `scrollable-region-focusable` on the article body's `<pre>`
 *    code block — generated by the markdown reading surface (task 8), NOT this test
 *    task's to redesign (Decision F). The `<pre>` node is `.exclude()`-d with this
 *    comment; everything else asserts zero.
 *  - CONTRAST gate protects the currently-AA-compliant PRIMARY text (H1s, body
 *    prose, masthead nav links, form inputs) from regression. The site's systemic
 *    `--fg-subtle`/accent sub-AA is design-token-owned: de-emphasis microcopy is
 *    excluded as intentional; load-bearing/interactive sub-AA text is a tracked
 *    owner defect (helpers/axe.ts `KNOWN_AA_DEFECTS`, memory
 *    `task-29-a11y-contrast-findings`), excluded to keep the BLOCKING gate green
 *    (`max_gate_repair_rounds: 0`) — surfaced, not buried.
 *
 * Landmarks are asserted with role locators (the axe landmark rules are
 * best-practice-tagged, outside wcag2a/aa — Decision C). Scans run panel-CLOSED so
 * the avatar island's transient dialog markup can't perturb landmark counts (memory
 * base-mounted-island-landmark-collision); the open panel gets its own scan below.
 */

const THEMES = ['light', 'dark'] as const;

// ----------------------------------------------------- (a) structural matrix
test.describe('a11y — structural axe matrix', () => {
  // Pin light so a dark CI runner pref can't flip the 'light' cells (plan R10);
  // dark cells seed rc-theme via forceTheme (stored value wins on first paint).
  test.use({ colorScheme: 'light' });

  for (const t of TEMPLATES) {
    for (const lang of LANGS) {
      for (const theme of THEMES) {
        test(`structural · ${t.name} · ${lang} · ${theme}`, async ({
          page,
        }) => {
          if (theme === 'dark') await forceTheme(page, 'dark');
          await page.goto(t[lang]);
          // `.exclude('pre')`: the article code block's scrollable-region-focusable
          // is a reading-surface (task 8) finding, recorded — not fixed in a test
          // task (Decision F). No other template has a <pre>, so this is a no-op
          // elsewhere.
          const { violations } = await structuralScan(page)
            .exclude('pre')
            .analyze();
          expect(violations).toEqual([]);
        });
      }
    }
  }
});

// --------------------------------------------------- (b) primary-text contrast
test.describe('a11y — primary-text contrast', () => {
  test.use({ colorScheme: 'light' });

  const SUBSET = TEMPLATES.filter((t) =>
    ['home', 'article', 'work-detail', 'about', 'search'].includes(t.name)
  );

  for (const t of SUBSET) {
    for (const lang of LANGS) {
      for (const theme of THEMES) {
        test(`contrast · ${t.name} · ${lang} · ${theme}`, async ({ page }) => {
          if (theme === 'dark') await forceTheme(page, 'dark');
          await page.goto(t[lang]);
          const { violations } = await contrastScan(page).analyze();
          // Zero on the remaining primary text; known sub-AA is excluded + tracked.
          expect(violations).toEqual([]);
        });
      }
    }
  }
});

// ----------------------------------------------------- (c) landmarks (explicit)
test.describe('a11y — landmarks (Decision C)', () => {
  test.use({ colorScheme: 'light' }); // landmarks are theme-invariant

  for (const t of TEMPLATES) {
    test(`landmarks · ${t.name}`, async ({ page }) => {
      for (const lang of LANGS) {
        await page.goto(t[lang]);
        await expect(
          page.getByRole('banner'),
          `one banner on ${t[lang]}`
        ).toHaveCount(1);
        await expect(
          page.locator('main#main'),
          `one main#main on ${t[lang]}`
        ).toHaveCount(1);
        await expect(
          page.getByRole('main'),
          `one main role on ${t[lang]}`
        ).toHaveCount(1);
        await expect(
          page.getByRole('contentinfo'),
          `one contentinfo on ${t[lang]}`
        ).toHaveCount(1);
        expect(
          await page.getByRole('navigation').count(),
          `>=1 navigation on ${t[lang]}`
        ).toBeGreaterThanOrEqual(1);
      }
    });
  }
});

// ------------------------------------------------- (d) skip-link + focus-visible
test.describe('a11y — skip-link & focus-visible', () => {
  test.use({ colorScheme: 'light' });

  /** True when `el` shows a non-`none` focus ring (outline OR box-shadow). */
  async function hasVisibleRing(locator: Locator): Promise<boolean> {
    return locator.evaluate((el) => {
      const s = getComputedStyle(el);
      const outline = s.outlineStyle !== 'none' && s.outlineWidth !== '0px';
      const shadow = s.boxShadow !== 'none' && s.boxShadow !== '';
      return outline || shadow;
    });
  }

  /** Press Tab up to `max` times until `locator` is the active element. */
  async function tabUntilFocused(locator: Locator, max = 15): Promise<boolean> {
    for (let i = 0; i < max; i++) {
      await locator.page().keyboard.press('Tab');
      const focused = await locator.evaluate(
        (el) => el === document.activeElement
      );
      if (focused) return true;
    }
    return false;
  }

  test('first Tab focuses the skip-link (→ #main) with a visible :focus-visible ring', async ({
    page,
  }) => {
    await page.goto('/en/');
    await page.keyboard.press('Tab');
    const skip = page.locator('a.skip-link');
    await expect(skip).toBeFocused();
    await expect(skip).toHaveAttribute('href', '#main');
    // Reached via a real keyboard event ⇒ :focus-visible matches (modality-gated).
    expect(await skip.evaluate((el) => el.matches(':focus-visible'))).toBe(
      true
    );
    expect(await hasVisibleRing(skip)).toBe(true);
  });

  test('FR sanity: first Tab focuses the skip-link', async ({ page }) => {
    await page.goto('/fr/');
    await page.keyboard.press('Tab');
    await expect(page.locator('a.skip-link')).toBeFocused();
  });

  test('masthead search trigger & theme toggle are keyboard-reachable and show a ring', async ({
    page,
  }) => {
    await page.goto('/en/');
    // Reach each via real Tab presses (NOT programmatic focus() — :focus-visible is
    // input-modality-gated in Chromium and would not match after a bare focus()).
    const trigger = page.locator('header [data-search-trigger]');
    expect(await tabUntilFocused(trigger), 'search trigger reachable').toBe(
      true
    );
    expect(await hasVisibleRing(trigger), 'search trigger ring').toBe(true);

    const toggle = page.locator('header .theme-toggle');
    expect(await tabUntilFocused(toggle), 'theme toggle reachable').toBe(true);
    expect(await hasVisibleRing(toggle), 'theme toggle ring').toBe(true);
  });

  test('opening the avatar launcher moves focus to its input', async ({
    page,
  }) => {
    await page.goto('/en/');
    await page.locator('[data-avatar-slot]').click();
    await expect(page.locator('[data-avatar-input]')).toBeFocused();
  });
});

// ------------------------------------------- (e) open avatar-panel a11y (§5.6e)
test.describe('a11y — open avatar panel (dynamic DOM)', () => {
  test('answer/citation DOM is structurally clean + the panel has dialog semantics', async ({
    page,
  }) => {
    await routeAvatar(page, GROUNDED_EN);
    await page.goto('/en/');

    const launcher = page.locator('[data-avatar-slot]');
    const panel = page.locator('[data-avatar-panel]');
    await launcher.click();
    const input = page.locator('[data-avatar-input]');
    await input.fill('Has Rachid built a RAG system?');
    await input.press('Enter');
    await expect(panel.locator('.rc-ans')).toBeVisible();

    // The matrix scans panel-CLOSED, so the JS-built citation links + cloned
    // templates are otherwise never axe-checked. Empirically clean (pre-scan);
    // Decision F applies if it ever regresses (a task-20 finding, not a here-fix).
    const { violations } = await new AxeBuilder({ page })
      .withTags([...AXE_TAGS])
      .disableRules(['color-contrast'])
      .include('[data-avatar-panel]')
      .analyze();
    expect(violations).toEqual([]);

    // Dialog semantics (task-20 contract): role + accessible name + aria-modal on
    // the panel, aria-expanded on the launcher.
    await expect(panel).toHaveAttribute('role', 'dialog');
    await expect(panel).toHaveAttribute('aria-modal', 'false');
    await expect(panel).toHaveAttribute('aria-label', /.+/);
    await expect(launcher).toHaveAttribute('aria-expanded', 'true');
  });
});
